version: "3.8"
services:
    nginx_dev:
          build: 
              context: ./nginx
              dockerfile: Dockerfile
          volumes:
              - ./public_html:/var/www/html
              - ./configs/nginx_conf/site.conf:/etc/nginx/conf.d/default.conf
          links:
              - php_dev
              - mysql_dev
    
    php_dev:
          container_name: php_dev
          build: 
              context: ./php
              dockerfile: Dockerfile
          ports: 
              - "10001:9000"
          volumes:
              - ./public_html:/var/www/html

    mysql_dev:
          container_name: mysql_dev
          build: 
              context: ./mysql
              dockerfile: Dockerfile
          ports: 
              - "10002:3306"
          volumes:
              - ./public_html:/var/www/html
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: TopSecret
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker

    nginx_loadbalancer:
          container_name: nginx_loadbalancer
          build: 
              context: ./nginx_loadbalancer
              dockerfile: Dockerfile
          ports: 
              - "10000:80"
          volumes:
              - ./configs/nginx_loadbalancer_conf/proxy.conf:/etc/nginx/conf.d/proxy.conf


