version: "3.8"
services:
    nginx:
          container_name: nginx
          build: 
              context: ./nginx
              dockerfile: Dockerfile
          ports: 
              - "10000:80"
          volumes:
              - ./public_html:/var/www/html
              - ./configs/nginx_conf/site.conf:/etc/nginx/conf.d/default.conf
          links:
              - php
              - mysql
    
    php:
          container_name: php
          build: 
              context: ./php
              dockerfile: Dockerfile
          ports: 
              - "10001:9000"
          volumes:
              - ./public_html:/var/www/html

    mysql:
          container_name: mysql
          build: 
              context: ./mysql
              dockerfile: Dockerfile
          ports: 
              - "10002:3306"
          volumes:
              - ./public_html:/var/www/html
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: TopSecret
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker


